language: node_js # 构建所需的语言环境
node_js: 
  - "v12.8.2"
branches:
  only:
  - master    # 构建的分支
cache:
  directories:
  - node_modules # 依赖缓存的目录
# before_install:
# - export TZ='Asia/Shanghai'  # 设置时区
install:
 - npm install -g gitbook-cli # 安装编译工具
script:
- gitbook build

after_script:
  - cd ./_book
  - git init
  - git config user.name "sarahchen"
  - git config user.email "eleven.chenxu@gmail.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

env:
  global:
    - GH_REF: github.com/SarahChenBJ/book.git

# deploy:
#   provider: pages
#   skip-cleanup: true
#   github-token: $GH_TOKEN # github 上的token环境变量
#   local-dir: ./_book/ ## 根据情况自定义到静态文件输出目录
#   target-branch: gh-pages
#   verbose: true
#   on:
#     branch: master
